### ISSUE TITLE
あるはずの作品ページが404になる

### ISSUE THREAD

**Issue by H37kouya** [u-lab/rebuilt-api#36]
## やること
原因解明

## 対象API
作品ページ GET (/api/v1/pages/{user}/storages/{storageID})

## エラー内容
```
[2020-04-03 18:18:55] local.ERROR: Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\Storage]. in C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:470
Stack trace:
#0 C:\Users\kouya\code\rebuilt\rebuilt-api\app\Repositories\Storage\StorageRepository.php(94): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\Users\kouya\code\rebuilt\rebuilt-api\app\Services\Pages\StorageService.php(69): App\Repositories\Storage\StorageRepository->get_storage_no_user_id('1581315433ra05d...')
#2 C:\Users\kouya\code\rebuilt\rebuilt-api\app\Http\Controllers\Pages\StorageController.php(59): App\Services\Pages\StorageService->get_user_storage(Object(App\Http\Requests\Pages\ShowStorageRequest), 'admin', '1581315433ra05d...')
#3 [internal function]: App\Http\Controllers\Pages\StorageController->show(Object(App\Http\Requests\Pages\ShowStorageRequest), 'admin', '1581315433ra05d...')
#4 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#5 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('show', Array)
#6 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Pages\StorageController), 'show')
#7 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController()
#8 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run()
#9 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#14 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#17 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#18 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#21 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\spatie\laravel-cors\src\Cors.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Spatie\Cors\Cors->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 C:\Users\kouya\code\rebuilt\rebuilt-api\app\Http\Middleware\SetLocale.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\itsgoingd\clockwork\Clockwork\Support\Laravel\ClockworkMiddleware.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Clockwork\Support\Laravel\ClockworkMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 C:\Users\kouya\code\rebuilt\rebuilt-api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 C:\Users\kouya\code\rebuilt\rebuilt-api\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 C:\Users\kouya\code\rebuilt\rebuilt-api\server.php(19): require_once('C:\\Users\\kouya\\...')
#42 {main}

```

**Comment by H37kouya** [comment]
フロント側のミスだった
